# Generated by Django 5.0.4 on 2024-05-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_campaign_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('date',)},
        ),
    ]
