# Generated by Django 5.0.4 on 2024-05-13 13:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_alter_campaign_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
