# Generated by Django 5.0.4 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_campaign_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='months',
            field=models.JSONField(default=list),
        ),
    ]
