# Generated by Django 5.0.4 on 2024-05-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_alter_campaign_months'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='months',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='slug',
        ),
    ]
