# Generated by Django 5.0.4 on 2024-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0007_remove_campaign_months_remove_campaign_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
