# Generated by Django 5.0.4 on 2024-05-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0008_campaign_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('month', models.IntegerField()),
                ('sent', models.IntegerField()),
                ('seen', models.IntegerField()),
                ('replied', models.IntegerField()),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
