# Generated by Django 5.0.4 on 2024-05-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0009_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={},
        ),
    ]
